import Link from "next/link";
import { Icon } from "@/components/icon";

export const metadata = { title: "About Us", description: "Learn about Rooted In Christ Ministry." };
const values = [
  ["Faith", "We are rooted in the life, teaching, and love of Jesus Christ."],
  ["Compassion", "We meet people with dignity, patience, and practical care."],
  ["Integrity", "We steward trust through honest records and responsible action."],
  ["Community", "We believe lasting change grows through shared participation."],
];

export default function AboutPage() { return <main id="main-content" className="simple-page"><section className="page-hero"><div className="container"><p className="eyebrow light">About the ministry</p><h1>Rooted in faith. Present in community.</h1><p>A ministry foundation for spiritual growth, compassionate service, and flourishing communities.</p></div></section><section className="container about-page"><div className="about-lead"><p className="eyebrow">Who we are</p><h2>A place for verified story, clear purpose, and shared hope.</h2><p>Rooted In Christ Ministry brings Christian faith, compassionate service, practical support, and community connection together. We share ministry information clearly and treat every person and story with dignity.</p></div><div className="about-purpose"><article><span>01</span><h3>Our mission</h3><p>To help people grow in Christ while serving individuals, families, and communities with compassion and integrity.</p></article><article><span>02</span><h3>Our vision</h3><p>To see faith expressed through stronger relationships, practical opportunity, and communities where people can flourish.</p></article></div><section className="values-section"><div className="section-heading"><div><p className="eyebrow">What guides us</p><h2>Values that take root.</h2></div><p>These commitments shape how we serve, communicate, and steward the trust placed in the ministry.</p></div><div className="values-grid">{values.map(([title, description]) => <article key={title}><span className="value-number">{title === "Faith" ? "01" : title === "Compassion" ? "02" : title === "Integrity" ? "03" : "04"}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="about-safeguard"><Icon name="sprout" size={29} /><div><strong>Responsible communication</strong><p>We publish ministry information with consent, context, and care. Personal details, financial information, and outcomes are shared only when appropriate and verified.</p></div></section><Link href="/contact" className="arrow-link">Contact the ministry <Icon name="arrow" size={18} /></Link></section></main>; }
