import Link from "next/link";
import { Icon } from "@/components/icon";

export const metadata = { title: "About Us", description: "Learn about Rooted In Christ Ministry." };
const values = [
  ["Faith", "We are rooted in the life, teaching, and love of Jesus Christ."],
  ["Compassion", "We meet people with dignity, patience, and practical care."],
  ["Integrity", "We steward trust through honest records and responsible action."],
  ["Community", "We believe lasting change grows through shared participation."],
];

export default function AboutPage() { return <main id="main-content" className="simple-page"><section className="page-hero"><div className="container"><p className="eyebrow light">About the ministry</p><h1>Rooted in faith. Present in community.</h1><p>A ministry foundation for spiritual growth, compassionate service, and flourishing communities.</p></div></section><section className="container about-page"><div className="about-lead"><p className="eyebrow">Who we are</p><h2>A place for verified story, clear purpose, and shared hope.</h2><p>The ministry’s history, leadership, registration information, and communities served will be published here from authorised source material. We will not fill these spaces with assumptions.</p></div><div className="about-purpose"><article><span>01</span><h3>Our mission</h3><p>To be added from the ministry’s approved mission statement.</p></article><article><span>02</span><h3>Our vision</h3><p>To be added from the ministry’s approved vision statement.</p></article></div><section className="values-section"><div className="section-heading"><div><p className="eyebrow">What guides us</p><h2>Values that take root.</h2></div><p>These values establish the content direction and can be refined by ministry leadership.</p></div><div className="values-grid">{values.map(([title, description]) => <article key={title}><span className="value-number">{title === "Faith" ? "01" : title === "Compassion" ? "02" : title === "Integrity" ? "03" : "04"}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="about-safeguard"><Icon name="sprout" size={29} /><div><strong>Content safeguard</strong><p>Leadership names, addresses, registration numbers, statistics, and regional claims will appear only after the ministry supplies and approves them.</p></div></section><Link href="/contact" className="arrow-link">Contact the ministry <Icon name="arrow" size={18} /></Link></section></main>; }
