"use client";
import { useActionState, useState, useTransition } from "react";
import { uploadMedia, type MediaState } from "@/app/admin/content/gallery/actions";
const initial: MediaState = { ok: false, message: "" };
async function thumbnail(file: File) {
  const bitmap = await createImageBitmap(file); const scale = Math.min(1, 1600 / Math.max(bitmap.width, bitmap.height));
  const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(bitmap.width * scale)); canvas.height = Math.max(1, Math.round(bitmap.height * scale));
  const context = canvas.getContext("2d"); if (!context) return file; context.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
  const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", 0.82));
  return blob ? new File([blob], file.name.replace(/\.[^.]+$/, ".jpg"), { type: "image/jpeg" }) : file;
}
export function AdminMediaForm() { const [state, action] = useActionState(uploadMedia, initial); const [clientMessage, setClientMessage] = useState(""); const [pending, startTransition] = useTransition(); const [preparing, setPreparing] = useState(false); const formAction = async (formData: FormData) => { const files = formData.getAll("files").filter((value): value is File => value instanceof File && value.size > 0); if (files.length > 20) { setClientMessage("Please upload no more than 20 images per batch."); return; } setClientMessage(""); setPreparing(true); try { const resized = await Promise.all(files.map(thumbnail)); formData.delete("files"); resized.forEach((file) => formData.append("files", file)); startTransition(() => action(formData)); } catch { setClientMessage("One of the selected images could not be prepared. Try JPG, PNG, or WebP files."); } finally { setPreparing(false); } }; return <form className="contact-form" action={formAction}><label>Gallery title<input name="title" required maxLength={180} placeholder="Used as the base title for each image" /></label><label>Images<input name="files" type="file" accept="image/jpeg,image/png,image/webp" multiple required /><small>Select up to 20 images. They will be resized to responsive thumbnails before upload.</small></label><label>Caption<textarea name="caption" rows={4} maxLength={500} /></label><button className="button" disabled={pending || preparing} type="submit">{preparing ? "Preparing thumbnails…" : pending ? "Uploading images…" : "Publish images to gallery"}</button>{(clientMessage || state.message) && <p className={clientMessage ? "form-error" : state.ok ? "form-success" : "form-error"} role="status">{clientMessage || state.message}</p>}</form>; }