-- Rooted In Christ Ministry foundation. Review and apply through Supabase migrations.
create extension if not exists pgcrypto;
create type public.user_role as enum ('super_admin','administrator','content_manager','programme_manager','volunteer_manager','beneficiary_manager','finance_manager');
create type public.record_status as enum ('draft','published','archived');
create type public.review_status as enum ('new','under_review','more_information_required','approved','declined','assistance_provided','closed');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, role public.user_role not null default 'content_manager', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.programmes (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, description text, category text not null, status public.record_status not null default 'draft', location text, start_date date, end_date date, objectives text, beneficiaries text, featured_image_path text, call_to_action text, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), programme_id uuid references public.programmes(id) on delete set null, title text not null, slug text not null unique, description text, status public.record_status not null default 'draft', location text, objectives text, start_date date, end_date date, beneficiaries_reached integer, featured_image_path text, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.gallery_items (id uuid primary key default gen_random_uuid(), title text, caption text, storage_path text not null, programme_id uuid references public.programmes(id) on delete set null, project_id uuid references public.projects(id) on delete set null, status public.record_status not null default 'draft', captured_on date, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table public.assistance_requests (id uuid primary key default gen_random_uuid(), request_type text not null, full_name text not null, email text, phone text, location text, details text not null, status public.review_status not null default 'new', internal_notes text, reviewed_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.volunteer_applications (id uuid primary key default gen_random_uuid(), full_name text not null, email text not null, phone text, location text, skills text, profession text, areas_of_interest text, availability text, preferred_programme text, previous_experience text, additional_notes text, status public.review_status not null default 'new', internal_notes text, reviewed_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.partnership_enquiries (id uuid primary key default gen_random_uuid(), organisation_name text not null, contact_name text, email text not null, phone text, partnership_type text, area_of_interest text, message text not null, status public.review_status not null default 'new', internal_notes text, reviewed_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.posts (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, content text not null, category text, featured_image_path text, seo_title text, seo_description text, status public.record_status not null default 'draft', author_id uuid references auth.users(id), published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.impact_statistics (id uuid primary key default gen_random_uuid(), label text not null, value integer not null check (value >= 0), period_start date, period_end date, status public.record_status not null default 'draft', created_by uuid references auth.users(id), created_at timestamptz not null default now());

create or replace function public.has_role(required_role public.user_role) returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and (role = required_role or role = 'super_admin')); $$;
alter table public.profiles enable row level security; alter table public.programmes enable row level security; alter table public.projects enable row level security; alter table public.gallery_items enable row level security; alter table public.assistance_requests enable row level security; alter table public.volunteer_applications enable row level security; alter table public.partnership_enquiries enable row level security; alter table public.posts enable row level security; alter table public.impact_statistics enable row level security;
create policy "published programmes are public" on public.programmes for select using (status = 'published');
create policy "published projects are public" on public.projects for select using (status = 'published');
create policy "published gallery is public" on public.gallery_items for select using (status = 'published');
create policy "published posts are public" on public.posts for select using (status = 'published');
create policy "published impact is public" on public.impact_statistics for select using (status = 'published');
create policy "programme managers manage programmes" on public.programmes for all using (public.has_role('programme_manager')) with check (public.has_role('programme_manager'));
create policy "programme managers manage projects" on public.projects for all using (public.has_role('programme_manager')) with check (public.has_role('programme_manager'));
create policy "content managers manage gallery" on public.gallery_items for all using (public.has_role('content_manager')) with check (public.has_role('content_manager'));
create policy "content managers manage posts" on public.posts for all using (public.has_role('content_manager')) with check (public.has_role('content_manager'));
create policy "admins manage impact" on public.impact_statistics for all using (public.has_role('administrator')) with check (public.has_role('administrator'));
create policy "beneficiary managers manage assistance" on public.assistance_requests for all using (public.has_role('beneficiary_manager')) with check (public.has_role('beneficiary_manager'));
create policy "volunteer managers manage applications" on public.volunteer_applications for all using (public.has_role('volunteer_manager')) with check (public.has_role('volunteer_manager'));
create policy "admins manage partnerships" on public.partnership_enquiries for all using (public.has_role('administrator')) with check (public.has_role('administrator'));
create policy "users can view own profile" on public.profiles for select using (id = auth.uid());
create policy "super admins manage profiles" on public.profiles for all using (public.has_role('super_admin')) with check (public.has_role('super_admin'));

insert into storage.buckets (id, name, public) values ('ministry-media','ministry-media',false) on conflict (id) do nothing;
create policy "media read access" on storage.objects for select using (bucket_id = 'ministry-media');
create policy "content managers upload media" on storage.objects for insert with check (bucket_id = 'ministry-media' and public.has_role('content_manager'));
create policy "content managers delete media" on storage.objects for delete using (bucket_id = 'ministry-media' and public.has_role('content_manager'));
